targets:
  tutorial:
    api: http://127.0.0.1:8080
    team: main
    token:
      type: Bearer
      value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJjc3JmIjoiYjE3ZDgxZmMwMWIxNDE1Mjk2OWIyZDc4NWViZmVjM2EzM2IyY2MxYWZjZjU3Njc1ZWYwYzY0MTM3MWMzNzI3OSIsImV4cCI6MTUyMjcwMjUwMCwiaXNBZG1pbiI6dHJ1ZSwidGVhbU5hbWUiOiJtYWluIn0.JNutBGQJMKyFzow5eQOTXAw3tOeM8wmDGMtZ-GCsAVoB7D1WHv-nHIb3Rf1zWw166FuCrFqyLYnMroTlQHyPQUTJFDTiMEGnc5AY8wjPjgpwjsjyJ465ZX-70v1J4CWcTHjRGrB1XCfSs652s8GJQlDf0x2hi5K0xxvAxsb0svv6MRs8aw1ZPumguFOUmj-rBlum5k8vnV-2SW6LjYJAnRwoj8VmcGLfFJ5PXGHeunSlMdMNBgHEQgmMKf7bFBPKtRuEAglZWBSw9ryBopej7Sr3VHPZEck37CPLDfwqfKErXy_KhBA_ntmZ87H1v3fakyBSzxaTDjbpuOFZ9yDkGA

resources:
   - name: demogit
     type: git
     source: {uri: "https://github.com/rheffernan/springdemo.git"}
   - name: buildcontainer
     type: docker-image
     source:
        repository: gradle 
        tag: 6.0.1-jre11
   - name: demowar
     type: s3
     source:
        bucket: rheffernan
        versioned_file: demo-0.0.1-SNAPSHOT.war
        access_key_id: KT5Y6U6LKWGPFT1A016F
        secret_access_key: p6fPB2MqUx5jjPjLhImGIDZPMzd4LfPltui0LBZY
        endpoint: http://10.1.34.198:9000/

jobs:
- name: prep
  public: true
  plan:
  - get: demogit
    trigger: true
  - get: buildcontainer
    trigger: true
  - task: finder 
    config:
       platform: linux
       image_resource:
          type: docker-image
          source:
             repository: openjdk
             tag: 11-jdk
       run:
          path: sh
          args:
             - -c
             - |
               find . -name build.sh
       inputs: [{name: demogit}]
  - task: builder
    config:
       platform: linux
       image_resource:
          type: docker-image
          source:
             repository: openjdk
             tag: 11-jdk
       inputs: [{name: demogit}]
       outputs: [{name: build/libs/demo-0.0.1-SNAPSHOT.war}]
       run:
          path: sh
          args:
             - -c
             - |
               cd demogit
               ./build.sh
  - task: finder2 
    config:
       platform: linux
       inputs: [{name: build/libs/demo-0.0.1-SNAPSHOT.war}]
       image_resource:
          type: docker-image
          source:
             repository: openjdk
             tag: 11-jdk
       run:
          path: sh
          args:
             - -c
             - |
               find . -name "*.war"
               find . -type d -exec ls -al {} \; 
  - put: demowar
    params:
       file: demogit/build/libs/demo-0.0.1-SNAPSHOT.war
  


- name: itest 
  public: true
  plan:
  - get: demowar
    passed: [prep]
    trigger: true
  - task: test
    config:
       platform: linux
       image_resource:
          type: docker-image
          source:
             repository: openjdk
             tag: 11-jdk
       inputs: [{name: buildcontainer}]
       run:
          path: sh
          args:
             - -c
             - |
               cd demogit
               ./test.sh
groups:
- name: main
  jobs:
      - prep
      - itest

